# Generated by Django 4.2.7 on 2025-11-16 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2025, 11, 16, 17, 10, 10, 333654))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2025, 11, 16, 17, 10, 10, 333661))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
